services:
  api:
    image: veiculesale-api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports: 
      - "${API_PORT}:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db-veiculos;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    depends_on:
      - db-veiculos

  db-veiculos:
    image: postgres:latest
    container_name: db-veiculos-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: