services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports: 
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db-veiculos;Database=veiculos;Username=sa;Password=SenhaForte!
    depends_on:
      - db-veiculos

  db-veiculos:
    image: postgres:latest
    container_name: db-veiculos-postgres
    environment:
      - POSTGRES_DB=veiculos
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=SenhaForte!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data