apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculesale-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veiculesale-api
  template:
    metadata:
      labels:
        app: veiculesale-api
    spec:
      containers:
      - name: veiculesale-api
        image: veiculesale:latest  
        imagePullPolicy: Never 
        ports:
        - containerPort: 8080  
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: veiculesale-secrets
              key: CONNECTION_STRING
        - name: ASPNETCORE_ENVIRONMENT 
          valueFrom:
            configMapKeyRef:
              name: veiculesale-config
              key: ASPNETCORE_ENVIRONMENT
---
apiVersion: v1
kind: Service
metadata:
  name: veiculesale-service
spec:
  type: NodePort 
  selector:
    app: veiculesale-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000