apiVersion: v1
kind: ConfigMap
metadata:
  name: veiculesale-config
data:
  POSTGRES_DB: "veiculos"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres-service"
  ASPNETCORE_ENVIRONMENT: "Development"