apiVersion: v1
kind: Secret
metadata:
  name: veiculesale-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  CONNECTION_STRING: "Host=postgres-service;Port=5432;Database=veiculos;Username=postgres;Password=postgres;"